name: npcx
main: net.gamerservices.npcx.npcx
version: 0.01
author: mixxit
website: http://www.gamerservices.net
description: >
    NPCExtender
commands:
    npcx:
        description: npc extender debugger